# Generated by Django 3.2 on 2022-08-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_key_size',
            field=models.BooleanField(blank='True', default='False', null='True'),
            preserve_default='True',
        ),
    ]
