# Generated by Django 3.2 on 2022-08-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_has_key_size_product_keyboard_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keyboard_size',
            field=models.IntegerField(blank='True', default='False', null='True'),
        ),
    ]
