# Generated by Django 3.2 on 2022-08-10 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_keyboard_size_product_has_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_keys',
            new_name='keyboard_size',
        ),
    ]
