# Generated by Django 3.2 on 2022-08-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='review_text',
        ),
    ]
