# Generated by Django 3.2 on 2022-08-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_body_review_review_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
