# Generated by Django 3.2 on 2022-08-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_review_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keyboard_size',
            field=models.IntegerField(blank='True', default='', null='True'),
        ),
    ]
